### ISSUE TITLE
Error in PPO Implementation

### ISSUE THREAD

**Issue by liziniu** [MorvanZhou/Reinforcement-learning-with-tensorflow#108]
Hi Morvan,
    In your implementations of PPO algorithms, before update the actor-network, the old actor-network will be replaced by the actor-network. Thus, during training, the ratio of pi(s, a)/oldpi(s, a) is always 1. 
    From my perspective,  here are 3 steps.
    1) copy the actor-network parameters.
    2) update the actor-network parameters.
    3) replace the old network with the copied parameters from step(1).

**Comment by MorvanZhou** [comment]
The pi is indeed the same as the oldpi at the first step of updating, means pi/oldpi = 1.
However, the update has many update steps, the second and third and so on will have pi/oldpi != 1. After those update steps, the pi will move to a better position and the next run starts by copying pi to oldpi with pi/oldpi = 1 again.
