### ISSUE TITLE
Question for Deep Q network

### ISSUE THREAD

**Issue by wetliu** [MorvanZhou/Reinforcement-learning-with-tensorflow#11]
Hi Morvan. 

I have a question about this line: https://github.com/MorvanZhou/Reinforcement-learning-with-tensorflow/blob/master/contents/5_Deep_Q_Network/DQN_modified.py#L86. Shouldn't it be self.s_ instead of self.s? Thank you!

**Comment by MorvanZhou** [comment]
You are right and thanks for finding the typo.
