### ISSUE TITLE
how to do ddpg on discrete?

### ISSUE THREAD

**Issue by jandevries123** [MorvanZhou/Reinforcement-learning-with-tensorflow#110]
How to make the ddpg code v2 applicable for a discrete action space? like the settings etc?

**Comment by MorvanZhou** [comment]
Hi DDPG architecture is not designed for discrete action. From my perspective, DQN is a better algorithm for discrete action.

**Comment by jandevries123** [comment]
Please be so kind to delete this issue for me, thank you in advance.
