### ISSUE TITLE
关于DQN的问题

### ISSUE THREAD

**Issue by CoNike** [MorvanZhou/Reinforcement-learning-with-tensorflow#111]
你好，我想问一下，我运行了你的DQN程序，并且稍微修改了一下环境。
![2019-01-08 15-35-52](https://user-images.githubusercontent.com/32361787/50816937-224f0100-135d-11e9-8eab-a629c6fe0f0e.png)
虽然它的cost是这样：
![2019-01-08 15-33-42](https://user-images.githubusercontent.com/32361787/50816960-3430a400-135d-11e9-9f38-6ff4d38d2cbf.png)
但是我在可视化的时候，几乎没有看见agent到达目标，这个是为什么呢？

**Comment by MorvanZhou** [comment]
cost 减小是因为他对环境越来越熟悉，但并不代表他能完成任务。感觉你需要增加探索度才能让agent完全熟悉环境。
