### ISSUE TITLE
强化学习模型怎么保存

### ISSUE THREAD

**Issue by liqinxiao** [MorvanZhou/Reinforcement-learning-with-tensorflow#112]
DQN模型要怎么保存，我现在想的训练完后保存q_eval神经网络的参数，然后再导入保存好的参数写到项目中，不知道有没有好的办法。

**Comment by MorvanZhou** [comment]
请参考一下我这一份代码：https://github.com/MorvanZhou/Tensorflow-Tutorial/blob/master/tutorial-contents/303_save_reload.py
而且在 Saver里可以自定义要保存的variables：
`tf.train.Saver(var_list=your_variables)`
