### ISSUE TITLE
Main function of run_this.py?

### ISSUE THREAD

**Issue by HalleyXie** [MorvanZhou/Reinforcement-learning-with-tensorflow#14]
Hi Morvan, many thanks for all your sharing.

I typed in all your 3 py files posted here, but when I run "python run_this.py" on windows, it shows up:

Traceback (most recent call last):
  File "run_this.py", line 47, in <module>
    RL = QLearningTable(actions=list(range(env.n_actions)))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\tki
nter\__init__.py", line 2095, in __getattr__
    return getattr(self.tk, attr)
AttributeError: '_tkinter.tkapp' object has no attribute 'n_actions'

It seems the n_action variable is not initialized. Not sure where the problem is. Could you help?

**Comment by MorvanZhou** [comment]
Hi, I do assign the n_actions to the __init__ function, please find in L33 in [here](https://github.com/MorvanZhou/Reinforcement-learning-with-tensorflow/blob/master/contents/2_Q_Learning_maze/maze_env.py#L33).
You can manually assign the actions' value in QLearningTable() if needed. I think the Windows version makes it behaves differently than others.

**Comment by HalleyXie** [comment]
Hi


Thank you for your response.


I got the problem resolved.


Best Regards,

Halley

________________________________
