### ISSUE TITLE
Q-learning vs. Sarsa_lambda

### ISSUE THREAD

**Issue by MHaneferd** [MorvanZhou/Reinforcement-learning-with-tensorflow#15]
Hi. Thanks for good tutorials!

You mentioned that Sarsa_lambda(4) was more efficient than the regular Q-learning(2), and it looks like it learn to get to the yellow target quicker.

However, when I modify the environment to be a 8x8 maze with 5 obstacles. The Q-learning seems to "get it faster", than Sarsa_lambda. Sarsa_Lamda, starts to explore, but after some falilures it starts more and more to camp in the corner (Afraid to explore? :-) )

Is this the way it should be, or I am missing something? 

Tried to attach my custom environment file:

[maze_env.txt](https://github.com/MorvanZhou/Reinforcement-learning-with-tensorflow/files/1350481/maze_env.txt)

**Comment by MorvanZhou** [comment]
Hi @MHaneferd , what you observed is quite normal in sarsa and it's the nature of sarsa. Sarsa is an on policy update. I believe when you lower the number of obstacles in 8x8 maze, sarsa-lambda would bring you a faster convergence. Alternatively, you can try to increase the exploring factor (epsilon), allowing sarsa to explore the env more. Once sarsa gets more positive reward signal, it will be better than q learning.
