### ISSUE TITLE
DDPG action 不需要normalize 吗？

### ISSUE THREAD

**Issue by YingxiaoKong** [MorvanZhou/Reinforcement-learning-with-tensorflow#157]
我看了你的DDPG的程序，对比了其他人的，觉得非常清晰。但是有一点我不太理解，就是我在论文里面也看到了action和state都需要normalize，但是在你的程序里面并没有看到，请问你是怎么处理呢？

**Comment by MorvanZhou** [comment]
这个看情况而定，是可以加上去的。因为测试用的游戏比较简单，state，action不normalize也是可以的。
