### ISSUE TITLE
ddpg算法没有收敛.没有复现视频的结果

### ISSUE THREAD

**Issue by zhangbo2008** [MorvanZhou/Reinforcement-learning-with-tensorflow#158]
![image](https://user-images.githubusercontent.com/35842504/73994352-33b77200-4990-11ea-9ba4-8dd632838bf3.png)

**Comment by MorvanZhou** [comment]
Refer to this issue, https://github.com/MorvanZhou/Reinforcement-learning-with-tensorflow/pull/125 

I have changed the code.
