### ISSUE TITLE
如何限制输出的动作不小于0？

### ISSUE THREAD

**Issue by YingxiaoKong** [MorvanZhou/Reinforcement-learning-with-tensorflow#159]
莫凡你好，非常感谢你之前的回复。 我的agent是一个自己定义的简单的模型。 就是一辆车在一条线上跑，但是只能往一个方向跑，所以它的速度只能是不小于0， 请问这个该怎么限制呢？
另外一个问题就是，我把每部的动作输出了一下，发现输出的动作一直在边界上，这是为什么呢？

**Comment by MorvanZhou** [comment]
1. 将action的取值映射到正值空间上就好了，比如tanh（-1，1）-> (0, 20).
2. 值在边界上说明agent已经不想在探索了，可以调小学习率，或者是调大探索率。
