### ISSUE TITLE
Simple PPO.py

### ISSUE THREAD

**Issue by zkx741481546** [MorvanZhou/Reinforcement-learning-with-tensorflow#163]
__init__ 函数中下面这行代码应该在分母加上epsilon，防止出现nan
ratio = self.pi.prob(self.tfa) / self.old_pi.prob(self.tfa)
也就是改为如下代码
ratio = self.pi.prob(self.tfa) / (self.old_pi.prob(self.tfa)+EPS)

**Comment by MorvanZhou** [comment]
谢谢，的确可能会出现nan
