### ISSUE TITLE
env_maze中为什么会出现这样的错误呢？每次中途退出都会这样

### ISSUE THREAD

**Issue by MiaCompiling** [MorvanZhou/Reinforcement-learning-with-tensorflow#169]
![image](https://user-images.githubusercontent.com/59831989/77911433-5e081a80-72c3-11ea-8c57-709319d15c0c.png)

**Comment by RoyE3BBB** [comment]
你应该是直接右上角交叉了迷宫窗口吧，
如果用pycharm的话在运行台终止就不会出现了

**Comment by MorvanZhou** [comment]
是不是因为Python或者tkinter版本不对的问题。
