### ISSUE TITLE
Why both AC and A3C examples use Value function not Q-function?

### ISSUE THREAD

**Issue by zsdonghao** [MorvanZhou/Reinforcement-learning-with-tensorflow#17]
Hi, thank you for your great work.

I have a quick question, I wonder why the critics of your AC and A3C examples use Value function but not Q-function?

Will Q-function can stablize the training of your CartPole AC example?

Many thanks.

**Comment by MorvanZhou** [comment]
I get used to saying value function for state value V(s), Q function for state-action value Q(s,a).
If you want to do Q-function in Cartpole or others with discrete action, it is better to use Q-learning rather then AC.
