### ISSUE TITLE
Simple_PPO 中最后一个state的值是否应该为0？

### ISSUE THREAD

**Issue by YingxiaoKong** [MorvanZhou/Reinforcement-learning-with-tensorflow#172]
莫凡你好，我看了你的程序，然后想起来我们老师课上讲过，最后一个state的q-value应该是0.我看了一点其他人的程序，有的人也把最后一个state 的返回值写为0，是否是真的需要呢？

**Comment by Dr-Tuski** [comment]
最后终止时总要给Q一个赋值吧？不然程序怎么走啊？
实际问题按实际物理意义来，不是0也可以

**Comment by MorvanZhou** [comment]
是的，需要按照模拟的实际情况来判断赋值多少。

**Comment by YingxiaoKong** [comment]
最后终值的时候是有一个reward,但是这个reward是达到最后一个状态的前一个状态的reward，而不是最后一个状态的。state(T-1) = reward; state(T) 是终止状态，没有下一个状态，奖赏都是根据下一个状态来给的，所以最后一个状态没有奖赏，也就没有累积奖赏，因此它的q value应该是0。不知道这样想对不对？


在 2020年4月21日，下午8:30，Dr-Tuski <notifications@github.com> 写道：

﻿

最后终止时总要给Q一个赋值吧？不然程序怎么走啊？
实际问题按实际物理意义来，不是0也可以

**Comment by MorvanZhou** [comment]
可以这么理解，不过有种情况是环境没有尽头，所以也不会有last state.

**Comment by YingxiaoKong** [comment]
是的，谢谢！


在 2020年4月22日，上午12:10，Morvan <notifications@github.com> 写道：

﻿

可以这么理解，不过有种情况是环境没有尽头，所以也不会有last state.
