### ISSUE TITLE
为什么a2c与a3c实现中actor的learning rate比critic的learning rate小？

### ISSUE THREAD

**Issue by Hins** [MorvanZhou/Reinforcement-learning-with-tensorflow#177]
是根据实验效果调的吗？

**Comment by MorvanZhou** [comment]
是的，你也可以根据自己的实验方案来调整这些参数

**Comment by Hins** [comment]
感谢回复，请问除了调learning rate之外，您还有其它经验，用于平衡actor收敛效果与critic收敛效果吗？我在实验中会经常遇到actor与critic收敛情况不均衡问题
