### ISSUE TITLE
Tensorflow v2 update

### ISSUE THREAD

**Issue by tessavdheiden** [MorvanZhou/Reinforcement-learning-with-tensorflow#188]
Hi MorvanZhou,

Your code was not compatible with tensorflow v2. Also, I've changed ArmEnv to be like the openai gym interface (ie. using box2d for action and observation space).

```
        self.action_space = spaces.Box(
            low=-self.u_max,
            high=self.u_max, shape=(self.action_dim,),
            dtype=np.float32)
        # node1 (l, d_rad, x, y),
        # node2 (l, d_rad, x, y)
        low = np.array([0, 0, 0, 0, 0, 100, 100])
        high = np.array([1, self.arm1l, self.arm1l, self.arm1l + self.arm2l, self.arm1l + self.arm2l, 300, 300])
        self.observation_space = spaces.Box(
            low=low,
            high=high
        )
```

Should I do a pull request?

Best,
Tessa

**Comment by MorvanZhou** [comment]
Thanks, which code have you upgraded to tf2?

**Comment by tessavdheiden** [comment]
The ddpg policy for the robot arm.

**Comment by MorvanZhou** [comment]
Oh, for that code, I have done the upgrading in this repo, https://github.com/MorvanZhou/RLarm thanks.
