### ISSUE TITLE
'terminal' in 2_Q_Learning_maze

### ISSUE THREAD

**Issue by freebooterish** [MorvanZhou/Reinforcement-learning-with-tensorflow#20]
In the project: 2_Q_Learning_maze, the constant 'terminal' has never been assigned to any variable, So，the statement "if s_ != 'terminal':" has never been matched, is this a small typo?

**Comment by MorvanZhou** [comment]
Please check the [code](https://github.com/MorvanZhou/Reinforcement-learning-with-tensorflow/blob/master/contents/1_command_line_reinforcement_learning/treasure_on_right.py), the` if S_ != 'terminal':` and `else:` have been executed as expected.
