### ISSUE TITLE
argmax() is deprecated, use idxmax() instead

### ISSUE THREAD

**Issue by yangliu28** [MorvanZhou/Reinforcement-learning-with-tensorflow#22]
It's a minor problem.
In "contents/1_command_line_reinforcement_learning/treasure_on_right.py", the first use of `argmax()` starts to produce warning that `argmax()` is deprecated. The program can still continue though. You might want to replace it with `idxmax()`, and instances in other files.

**Comment by MorvanZhou** [comment]
Thanks, I decided to make a note on that line.
