### ISSUE TITLE
Substitute pandas `ix` with `iloc`.

### ISSUE THREAD

**Issue by alexpantyukhin** [MorvanZhou/Reinforcement-learning-with-tensorflow#24]
The `ix` function is seems to be deprecated. http://pandas.pydata.org/pandas-docs/version/0.20.3/whatsnew.html#deprecate-ix
Could be substitute with `iloc` in many cases.

**Comment by MorvanZhou** [comment]
Thanks for the note, I changed it to .loc instead.
