### ISSUE TITLE
為什麼合併Q的時候要將A減去他的平均值?

### ISSUE THREAD

**Issue by HencyChen** [MorvanZhou/Reinforcement-learning-with-tensorflow#27]
莫大大你好，你在影片中有提到為了避免V=0讓A直接等於Q，所以要將A減去他的均值。這邊我有個問題:
1. 為什麼不減去均值V就會直接等於0?
2. 為什麼剪了均值後A就不會直接等於Q?
謝謝!

**Comment by MorvanZhou** [comment]
因为每一个v 的大小都不一样，有一种让随机数打乱Q 的感觉. 这样A 就不完全依赖于Q

**Comment by HencyChen** [comment]
但這個的前提是V=0時A才會完全依賴於Q，但為什麼V一定會等於0呢?

**Comment by MorvanZhou** [comment]
我们想要的是A不要只依赖于Q, 所以要让 A = Q - V. 而不是 A = Q.
