### ISSUE TITLE
The hidden layers of A3C have too many neurons

### ISSUE THREAD

**Issue by sbyNiceBlowJob** [MorvanZhou/Reinforcement-learning-with-tensorflow#28]
The hidden layers of A3C have too many neurons. The input of Cartpole only has 4 parameters. Reduce the number 200 and 100 to 24, and the result should be a lot better.
A3C网络里隐藏层神经元设太多了，Cartpole的输入只有4个参数，设成200和100很难收敛，改成24收敛快很多，效果也好很多。

**Comment by MorvanZhou** [comment]
In my machine, the original settings have a better or just the same performance. However, the lower neurons number has the same effect as the high number. I'm using 4 workers BTW.

**Comment by sbyNiceBlowJob** [comment]
Would you please tell me your average score on CartPole?

**Comment by MorvanZhou** [comment]
It achieves 200+ at the end of training

**Comment by sbyNiceBlowJob** [comment]
请问怎么打印网络的loss？

**Comment by MorvanZhou** [comment]
Try this:
`sess.run(your_loss, {tfx: x, tfy:y})`

**Comment by sbyNiceBlowJob** [comment]
为什么A3C训练Mountcar的时候，收敛反而没有普通的policy gradient好？

**Comment by MorvanZhou** [comment]
原因可能有很多, 比如 reward 的定义, 学习率等等.
