### ISSUE TITLE
Questions regarding DQN_modified

### ISSUE THREAD

**Issue by EveLIn3** [MorvanZhou/Reinforcement-learning-with-tensorflow#29]
Hi,

In your updated DQN_modified in the DQN folder, how did you do the indexing for q_eval_wrt_a?

`with tf.variable_scope('q_eval'):`

`
               a_indices = tf.stack([tf.range(tf.shape(self.a)[0], dtype=tf.int32), self.a], axis=1)
               self.q_eval_wrt_a = tf.gather_nd(params=self.q_eval, indices=a_indices)    # shape=(None, )
`

Wouldn't tf.shape(self.a)[0] be referring to the num_of_actions(4 in the maze env)? but the quantity is 32 instead of 4 which is passed from the environment. I tried to print a using eval() and i got:
[[ 0  3]
 [ 1  3]
 [ 2  3]
 [ 3  0]
 [ 4  3]
 [ 5  3]
 [ 6  3]
 [ 7  3]
 [ 8  3]
 [ 9  3]
 [10  3]
 [11  3]
 [12  3]
 [13  0]
 [14  3]
 [15  3]
 [16  1]
 [17  3]
 [18  3]
 [19  2]
 [20  3]
 [21  3]
 [22  3]
 [23  3]
 [24  3]
 [25  3]
 [26  3]
 [27  3]
 [28  0]
 [29  3]
 [30  3]
 [31  0]]
Then you apply index-slicing on q_eval_wrt_a, so it will be q_eval_wrt_a[#Batch][action_index]?
What is the intuition of this? 
A little bit explanation on this will be greatly helpful. 
Thank u!

**Comment by MorvanZhou** [comment]
Hi,` tf.range(tf.shape(self.a)[0]` will give the batch index, and  `self.a` in `a_indices` is the column index. If you want to use `tf.gather_nd()` to get the corresponding `q`, you have to fit [batch_index, n_action] this style into it. The detail of the usage can be found in [here](https://www.tensorflow.org/api_docs/python/tf/gather_nd).
