### ISSUE TITLE
Save model in "experiments/Solve_LunarLander/A3C.py"

### ISSUE THREAD

**Issue by joseska** [MorvanZhou/Reinforcement-learning-with-tensorflow#32]
Hi....
How can I save the model in "experiments/Solve_LunarLander/A3C.py"

Thanks.....

**Comment by MorvanZhou** [comment]
Hi, 
You have to define your own "save" function in https://github.com/MorvanZhou/Reinforcement-learning-with-tensorflow/blob/master/experiments/Solve_LunarLander/DuelingDQNPrioritizedReplay.py

```
def save(self, path):
     # use tensorflow save function to save in "path"
```

**Comment by joseska** [comment]
Thanks.... But A3C.py don´t use DuelingDQNPrioritizedReplay.py.

**Comment by MorvanZhou** [comment]
Oh, sorry, I thought it was "run_LunarLander.py", cause in this file, it uses "DuelingDQNPrioritizedReplay.py". Anyway, you can only save the global net's variables in A3C.
