### ISSUE TITLE
Better Exploration with Parameter Noise

### ISSUE THREAD

**Issue by dynamik1703** [MorvanZhou/Reinforcement-learning-with-tensorflow#35]
Hey MorvanZhou,

first thanks for your really amazing expert work! Your repo is my favorite GitHub repo to learn about Reinforcement Learning!

Matthias Plappert has presented an impressive alternative to the action noise. It is called Parameter Noise:
https://blog.openai.com/better-exploration-with-parameter-noise/
https://github.com/openai/baselines/blob/master/baselines/ddpg/noise.py

Do you think this could be interesting for your repository? To compare and teach it?

Do you think it's easy to embed?

Best,
Roman

**Comment by MorvanZhou** [comment]
Hi I actually did an openai [ES method](https://blog.openai.com/evolution-strategies/) for reinforcement learning, which is a similar method to what you mentioned above.
Here is my implementation of that method.
https://github.com/MorvanZhou/Evolutionary-Algorithm/blob/master/tutorial-contents/Using%20Neural%20Nets/Evolution%20Strategy%20with%20Neural%20Nets.py

**Comment by dynamik1703** [comment]
Evolution strategies are interesting as well for hyperparameter optimization.

Do you have some algorithms for this?
