### ISSUE TITLE
q_learning中 maze_env.py报错

### ISSUE THREAD

**Issue by nuass** [MorvanZhou/Reinforcement-learning-with-tensorflow#38]
运行Q_learning的maze_env.py文件中错误，
请问莫凡大神这是哪里的问题？？tk的版本问题吗
---------------------
/usr/lib/python3.6/tkinter/__init__.py in __init__(self, screenName, baseName, className, useTk, sync, use)
   2018                 baseName = baseName + ext
   2019         interactive = 0
-> 2020         self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
   2021         if useTk:
   2022             self._loadtk()

TclError: no display name and no $DISPLAY environment variable

**Comment by MorvanZhou** [comment]
你是用ssh remote 到其他电脑的吗？
