### ISSUE TITLE
如何实现A3C代码中仅save全局网络的参数，而非所有参数

### ISSUE THREAD

**Issue by xiaokeZuo** [MorvanZhou/Reinforcement-learning-with-tensorflow#44]
MorvanZhou：
您好！
想问下，A3C代码中，在代码中仅有一个graph和一个session的情况下，如何实现仅save globalNet的参数以供后续使用？是不是只能够通过操作save函数要保存的参数列表？换成多进程来实现仅save globalNet的参数是不是更方便些？

谢谢
zxk

**Comment by MorvanZhou** [comment]
在 tensorflow 的网站中, 他提到过只保留选定 variable 的方法, 可以参考这里: Choose variables to save and restore

https://www.tensorflow.org/programmers_guide/saved_model
