### ISSUE TITLE
我应该如何输出我的应对策略表

### ISSUE THREAD

**Issue by Ostnie** [MorvanZhou/Reinforcement-learning-with-tensorflow#46]
在2_Q_Learning_maze中您初始化了一个网格，加入我现在把他看成16种状态（4*4），我应该如何输出他在每一种状态时选择的action？也就是说，我想通过RL得到一个完整的应对策略表我应该如何修改代码？以及我能否观察收敛速度，因为我想对比不同的算法看看效果。
在这里感谢一下您的工作，真的很伟大，而且很通俗易懂。

**Comment by MorvanZhou** [comment]
state-action Q table 是一个表, action 的种类不变, 你改变状态的话, 就相当于给每一个状态一个特殊的 ID, 让他能对应上这个表里16个位置. 观看收敛速度的话, 你打印出每回合获得的 reward 就行.
