### ISSUE TITLE
qlearning等算法讲的不透彻

### ISSUE THREAD

**Issue by freelogic** [MorvanZhou/Reinforcement-learning-with-tensorflow#48]
网上其实资料不少，但需要整理和讲透撤，就需要自身实力。
境界1. 自己看懂
境界2. 让别人明白

这第二点就特别难。因为兴趣基于明白其真理的欲望，所以真理和原理对需要研究的人最重要。对入门跑跑helloworld可能不需要。当下，最难的可能是深度和强化入门容易，学习曲线和数学基础不需要太高深。但问题是，入门之后要用好，要研究心算法，必须哲学层面透彻理解这些算法。

楼主入门资料非常好，不多说，qlearning和sarsa算法的原理层面讲解不透彻。
推荐一篇，https://www.zhihu.com/question/26408259
第一个讲解的不错，第二个博士在读的讲错了可以忽略。

期望能将您的形式丰富多彩的入门课程，逐步发展为中级，甚至高级的研究资料，这样您的能力至少接近了斯坦福的上课教授，比如李飞飞，如果走学院派，估计你以后也会带徒弟，如果是业界工作，到不需要。

最后，感谢您认真细致的资料，对入门帮助很大，看了即便。

**Comment by MorvanZhou** [comment]
谢谢.
