### ISSUE TITLE
AC_CartPole.py may need to consider the distance between cart to the center

### ISSUE THREAD

**Issue by zsdonghao** [MorvanZhou/Reinforcement-learning-with-tensorflow#5]
Hi, I think `AC_CartPole.py` may need to consider the distance between cart to the center.

Simply adding `r -= abs(s_[0]) * .1` to the reward.

**Comment by MorvanZhou** [comment]
Hi @zsdonghao , thanks for the suggestion.

I tried adding that line into the code, but it seems not helping. Maybe the approximated V(s_) and V(s) still are the problem.

I will close the issue, but feel free to reopen.
