### ISSUE TITLE
如果reward 十分稀疏，A3C UPDATE_GLOBAL_ITER 该如何选取

### ISSUE THREAD

**Issue by mas17kaworu** [MorvanZhou/Reinforcement-learning-with-tensorflow#50]
首先十分感谢您耐心解答了我前一个问题。
最近在套用您的A3C框架做一个玩小游戏的AI，有一个问题这段时间比较困扰我。
https://github.com/MorvanZhou/Reinforcement-learning-with-tensorflow/blob/9c27c8537b4722a683f96dee7d3fd8efc0b925e1/experiments/Solve_LunarLander/A3C.py#L29
我的游戏有点像吃豆子小人游戏，在一个地图中有很多糖果，控制的agent上下左右移动去获取糖果。
reward 的定义就是这一步吃到糖果reward 就是1，否则agent移动reward 都是0。这样会导致reward list 的正reward 十分稀疏。
您例子中reward都比较连续，这样感觉UPDATE_GLOBAL_ITER 比较小的话训练比较有效率。但是如果 reward十分稀疏的话 UPDATE_GLOBAL_ITER 该如何适应呢？或者有什么别的思路可以解决这一问题呢？
再次感谢！

**Comment by MorvanZhou** [comment]
最好的方法是讲 reward 改成连续的. UPDATE_GLOBAL_ITER 比较大的话, 随之是训练时间延长, 很慢才能看到效果. 比较小的话, 训练得快, 但是对于稀疏 reward 的效果不太好. 所以这也是一个 tradeoff
