### ISSUE TITLE
mu, sigma = mu * A_BOUND[1], sigma + 1e-4

### ISSUE THREAD

**Issue by michelliming** [MorvanZhou/Reinforcement-learning-with-tensorflow#53]
请问 A3C的连续动作 算法中， mu * A_BOUND[1]的含义是?  sigma加上一个很小的值是防止 sigma变得很小，失去了探索？

**Comment by MorvanZhou** [comment]
mu 的取值是-1～1，所以乘一个缩放参数。sigma加一个小的数为了避免无限接近零。无限接近零的话计算会报错。

**Comment by michelliming** [comment]
感谢 morvan，回复效率很高！
