### ISSUE TITLE
why there is some ‘nans’ stored in the self.tree.tree arrays?

### ISSUE THREAD

**Issue by zengjie617789** [MorvanZhou/Reinforcement-learning-with-tensorflow#54]
![image](https://user-images.githubusercontent.com/25050291/40895073-ef6ec942-67df-11e8-8ede-ac55af20471e.png)

**Comment by MorvanZhou** [comment]
The cause may be your TD error, something happens in the calculation of TD. When TD is NaN, your sumtree value will be NaN as well.
