### ISSUE TITLE
sum tree capacity in prioritized experienced replay

### ISSUE THREAD

**Issue by XavierDDD** [MorvanZhou/Reinforcement-learning-with-tensorflow#57]
Hi @MorvanZhou, thanks for this repo.

Recently I've tried the DQN with prioritized replay, and I found that there may be mistakes in the original implementation of SumTree if the capacity of memory is not exponential of 2.

self.tree = np.zeros(2 * capacity - 1)

In my understanding, the implementation of sum tree is a complete binary tree, so the number of  internal nodes will be pow(2, ceil(log( capacity, 2))) - 1.

The tree needs at least num_of_internal_nodes + capacity.
Is this right? 
Thanks

**Comment by MorvanZhou** [comment]
Hi,
Please refer to this link as my sumtree is a modified version based on this introduction.
https://jaromiru.com/2016/11/07/lets-make-a-dqn-double-learning-and-prioritized-experience-replay/
In this blog, there is a figure about a typical structure of the sumtree.

**Comment by XavierDDD** [comment]
Sorry, it's my misunderstanding.
The sum-tree implementation is different from binary heap. It's not a complete binary tree. 
Thanks.
