### ISSUE TITLE
DPPO只推送数据会加速很多吗？

### ISSUE THREAD

**Issue by songjs1993** [MorvanZhou/Reinforcement-learning-with-tensorflow#60]
莫烦你好，看了你做的强化学习系列视频，对DPPO实现部分有点疑问：

在你实现的DPPO中，如果不推送 gradient,，只是推送 collected data，为什么速度会增加那么多？我理解的即使拿到了多个worker探索的数据，计算梯度的时候还是需要计算当前实时参数下的概率π(a_t|s_t | theta)，而这个计算和actor直接sample一条路径耗费相差不多？（我理解actor网络都要前向计算一遍，只是sample路径时会再多一个多项分布采样的过程）

觉得效率不会差别这么大？不知是否能从实践经验上解释下？

先谢过~

**Comment by MorvanZhou** [comment]
可以参考一下这一篇论文，他们也是直接推observation。里面描述了这样做的好处。

ESPEHOLT, L., SOYER, H., MUNOS, R., SIMONYAN, K., MNIH, V., WARD, T., DORON, Y., FIROIU, V., HARLEY, T., DUNNIN, I., LEGG, S. & KAVUKCUOGLU, K. 2018. IMPALA: Scalable Distributed Deep-RL with Importance Weighted Actor-Learner Architectures. ArXiv e-prints [Online], 1802. Available: https://arxiv.org/abs/1802.01561v2.
