### ISSUE TITLE
Actor-Critic中，每轮训练，是先取td_error还是先训练critic再取td_error?

### ISSUE THREAD

**Issue by songjs1993** [MorvanZhou/Reinforcement-learning-with-tensorflow#62]
莫烦你好，AC_CartPole.py文件中，critic的学习
`    
def learn(self, s, r, s_):
        s, s_ = s[np.newaxis, :], s_[np.newaxis, :]

        v_ = self.sess.run(self.v, {self.s: s_})
        td_error, _ = self.sess.run([self.td_error, self.train_op],
                                          {self.s: s, self.v_: v_, self.r: r})
        return td_error
`
我不确定这里[self.td_error, self.train_op]一起run会是下面两种哪种情况，当然这个我自己试下即可，这里主要想问下这两种的区别：
（一）先取td_error再训练critic（Reinforcement Learning: An Introduction中伪码是这样）
（二）但另外一种操作：先训练critic再取td_error，这样会不会让当前batch中critic预测状态s的value值更准确？会不会更好？

**Comment by MorvanZhou** [comment]
我觉得应该先td error会理论上好一些，我的想法是。

1 td error
2 train actor(td error) and critic

先对网络当前的状态算td error， 对当前状态的Actor使用这个td error， 然后再训练critic。使得Actor 和critic一直保持在同一个状态。我是这么理解的。

**Comment by songjs1993** [comment]
多谢👌
