### ISSUE TITLE
对于CartPole任务，AC似乎表现不如Policy Gradient？

### ISSUE THREAD

**Issue by songjs1993** [MorvanZhou/Reinforcement-learning-with-tensorflow#63]
从原理上看，AC单步训练，应该学习效率收敛更快？
但对CartPole任务来说，PG更好一些？您觉得什么造成这个结果呢？ 
感谢！

**Comment by MorvanZhou** [comment]
AC中的C出来的是A更新的依据，如果C没训练好，A就训练不好。而C如果没有类似DQN那一套系统的话，比较难收敛。
对比PG，PG就只训练一个Actor，是你来reward engineering代替C来提供的一个“td-error”, 所以这样的PG比AC更单纯，只要你reward engineering出来的东西好，那么你就相当于你提供了一个很好的C，A也就训练得好。

**Comment by songjs1993** [comment]
那我基本可以理解为如果critic训练的不好，还不如不用；

请问你有在实践中哪个任务上做出AC效果比PG好的吗？  @MorvanZhou

**Comment by MorvanZhou** [comment]
我的实践告诉我，我的AC代码比PG更难train

**Comment by songjs1993** [comment]
嗯嗯了解了  多谢👌

**Comment by LiDuan1111** [comment]
AC在离散的cartpole中好像收敛不下来（一直在振荡，且分数上不去）……请问您多少个episode后才收敛的呢？

**Comment by LiDuan1111** [comment]
> 我的实践告诉我，我的AC代码比PG更难train

@MorvanZhou AC在离散的cartpole中好像收敛不下来（一直在振荡，且分数上不去）……请问您多少个episode后才收敛的呢？

**Comment by MorvanZhou** [comment]
@LiDuan1111 的确很难收敛，而且很多时候是收敛不了的。建议使用其他算法。
