### ISSUE TITLE
ppo algorithm question

### ISSUE THREAD

**Issue by weihaosky** [MorvanZhou/Reinforcement-learning-with-tensorflow#65]
In this line "ratio = pi.prob(self.tfa) / oldpi.prob(self.tfa)" . Should the pi be the same with oldpi? Because you update oldpi with pi. Then the ratio is 1 and the algorithm has no use. Do I understand it right?

**Comment by MorvanZhou** [comment]
There is a loop for update actor many times by using the same batch of data, the first time of updating will give a `ratio` of 1, but after the first update, the rest of updating will show different value rather than 1.

**Comment by weihaosky** [comment]
Thank you for the responding. Update the actor many times with the same data? It seems strange. But anyway at the first update of the loop the ratio does not work so it is the same with actor-critic, right? Then the actor can diverge in this update.
