### ISSUE TITLE
OpenAI gym:observation

### ISSUE THREAD

**Issue by byf061826** [MorvanZhou/Reinforcement-learning-with-tensorflow#68]
I want to know where to find the environment of atari-games, and I don't understand the meaning of the observations.

**Comment by MorvanZhou** [comment]
The observation means what the agent can see/feel/get, then base on them to take a particular action. Atari environment can be found in [here](https://gym.openai.com/envs/#atari).

**Comment by byf061826** [comment]
Sorry,I didn't express myself clearly. I mean that I cannot find the definition of observation-class in python packages. I think the reward function is from the observation, so I want to know the meaning of the every single observation. But I find that the dimension of the observation in atari-game is large, maybe I am wrong.
