### ISSUE TITLE
生成的图片意味着什么呢？

### ISSUE THREAD

**Issue by huangh12** [MorvanZhou/Reinforcement-learning-with-tensorflow#7]
莫烦你好，我运行了run_this.py，结果生成的cost图片如下：

![figure_1](https://user-images.githubusercontent.com/18748036/28979584-ed4a5764-797c-11e7-8439-6160c95f059b.png)

可是从图中看来，到了训练末尾，好像loss还没有收敛呢，那么这个图说明了什么呢？
谢谢！

**Comment by MorvanZhou** [comment]
你好，请参考这下这里对rl cost的说明。
https://morvanzhou.github.io/tutorials/machine-learning/reinforcement-learning/4-3-DQN3/#cost

**Comment by huangh12** [comment]
噢噢，谢谢你啊。既然cost不是非得平滑下降，那么我们应该根据什么来获知DQN（或者一般的RL算法）的学习的进度呢？
