### ISSUE TITLE
跑2_Q_learning_maze历程时发现训练结果不对

### ISSUE THREAD

**Issue by wdxairforce** [MorvanZhou/Reinforcement-learning-with-tensorflow#71]
1、操作系统是linux mint 18
2、python 版本是 python3.5
3、代码是clone目前最新版本的代码
4、程序是在pycharm中运行的，不是在终端运行
问题描述：在跑2_Q_learning_maze历程时没有出现视频中那种一开始乱撞，后面能找到正确的路径的效果，整个过程都在乱撞，一开始怀疑训练次数太少，但是昨晚跑了一晚上早上过来一看开始没有训练出正确的效果，我刚刚接触机器学习领域的内容，不懂得该如何调试这种问题，希望能得到您的帮助

**Comment by liyiying** [comment]
是的，我跑了一下也是出现如你所说问题。原因在于莫烦代码中RL_brain中choose_action方法中state_action = state_action.reindex(np.random.permutation(state_action.index))一句使用错误，也就是说这样的话只是把index随意打乱了，但里面的Q值顺序并没有改变。

**Comment by liyiying** [comment]
@wdxairforce 是的，我跑了一下也是出现如你所说问题。原因在于莫烦代码中RL_brain中choose_action方法中state_action = state_action.reindex(np.random.permutation(state_action.index))一句使用错误，也就是说这样的话只是把index随意打乱了，但里面的Q值顺序并没有改变。

**Comment by liyiying** [comment]
@MorvanZhou hi, Morvan, there is a small but important problem in your "RL_brain.py" of "2_Q_learning_maze" code. 
I have changed your code 
"state_action = state_action.reindex(np.random.permutation(state_action.index))" to 
            state_action_value = np.array(state_action)
            permutation = list(np.random.permutation(len(self.actions)))
            shuffled_index = state_action.index[permutation]
            shuffled_array = state_action_value[permutation]
            state_action = pd.Series(shuffled_array, index = shuffled_index)
then it works correctly! （虽然我不知道还有没有更好的直接的表达方式）
    By the way, 我有个在思考的小问题：在类似这样的环境中，其实智能体有多条路可以到达目的地，怎么让它学会知道“有很多条路可以到达，只要我避开陷进即可”？ 现在能实现的只是它学会到达目标（或者说从运行原理和效果上来看是学会了能够到达目标的最短的一条）。
    －－作为与你同龄并在Changsha的小PhD菜鸟，请不吝赐教～～

**Comment by MorvanZhou** [comment]
我修改了代码，现在应该没问题了
```
state_action = self.q_table.loc[observation, :]
# some actions may have the same value, randomly choose on in these actions
action = np.random.choice(state_action[state_action == np.max(state_action)].index)     
```
