### ISSUE TITLE
why no action required in value function?

### ISSUE THREAD

**Issue by sezan92** [MorvanZhou/Reinforcement-learning-with-tensorflow#72]
Hello, thanks for the clear code. I was going through your code, and I saw that while using the value function, you didnt use the action , instead you used only the state. from david silvers lecture , I have come to know the following 
![pseudocode actor critic](https://user-images.githubusercontent.com/11025093/43569884-d79ca70e-9673-11e8-8221-a56a35317b87.png)
We will need actions a and a' to get the values Q(s,a) and Q(s',a') . But you only used s and s'. can you explain?

**Comment by MorvanZhou** [comment]
In the calculation of the TD error, I use state value (V) instead of state-action value (Q). This is up to you to choose whether the V or Q in the calculation. You can find some discussions in the slide of "Estimating the Advantage Function (2)" in his PPT.
