### ISSUE TITLE
DDPG env not working

### ISSUE THREAD

**Issue by jandevries1421353151** [MorvanZhou/Reinforcement-learning-with-tensorflow#74]
hey i am trying to add my own environment to gym and then to the DDPG but i come accros several issues with gym and my env code. especially in

s_dim = env.observation_space.shape[0]
a_dim = env.action_space.shape[0]
a_bound = `env.action_space.high

ddpg = DDPG(a_dim, s_dim, a_bound) since i don't have that in the env, aswell for the mazeenv so what is it and what should it be changed to? also if @MorvanZhou could add me on skype or discord would be great if you want to answer more of my questions....

if i want to use pictures as input how should i make this?

**Comment by MorvanZhou** [comment]
Please refer to this one: https://github.com/openai/gym/tree/master/gym/envs
