### ISSUE TITLE
Could DDPG made without using Gym?

### ISSUE THREAD

**Issue by jandevries1421353151** [MorvanZhou/Reinforcement-learning-with-tensorflow#76]
Could there be a version that doesn't require gym?
cause for changing the code to your own environment i found that to hard...

could there just be that i can return values thru env.reset and env.step without using gym etc? easier?
or atleast then a tutorial on how to modify this code to your own environment instead of the gym environmnets

**Comment by MorvanZhou** [comment]
Yes I made some code that doesn't require gym. Please refer to here: https://github.com/MorvanZhou/Reinforcement-learning-with-tensorflow/tree/master/experiments/Robot_arm
