### ISSUE TITLE
三维observation应该如何处理DQN？

### ISSUE THREAD

**Issue by AlisaBen** [MorvanZhou/Reinforcement-learning-with-tensorflow#78]
莫烦你好~想问下当游戏环境是类似于Atari中的游戏时，observation会有多个维度，问下这时应该如何处理DQN？

**Comment by MorvanZhou** [comment]
你好，你需要了解一下gym中Atari的observation说明， 里面的observation应该是3维的图片输出。CNN+DQN就能解决这个问题。
