### ISSUE TITLE
A writing mistake in DoubleDQN?

### ISSUE THREAD

**Issue by YifanZhou95** [MorvanZhou/Reinforcement-learning-with-tensorflow#79]
Hi,

Thanks for your organized project about DeepRL. 

But it is confusing in Double_DQN/RL_brain.py line 148
`selected_q_next = np.max(q_next, axis=1)    # the natural DQN`
Since `q_next` is from target network, should it be as follow:
`selected_q_next = np.max(q_eval4next, axis=1)    # the natural DQN`

Could you explain it? 
Thank you.

**Comment by MorvanZhou** [comment]
Hi,
In natural DQN. The q_next is from target_net, and the first method `np.max(q_next, axis=1)` is selected.  The natural DQN is the DQN from [this](https://morvanzhou.github.io/tutorials/machine-learning/reinforcement-learning/4-2-DQN2/) tutorial.

**Comment by cuijiaxun** [comment]
I think the Double DQN you implemented is kind of different from what stated in the article. The loss should be the squared loss of chosen q and y double, both of which should have the shape (Batchsize,1) or (Batchsize,), instead of (Batchsize, action space)
