### ISSUE TITLE
car_env.py  SyntaxError

### ISSUE THREAD

**Issue by zhaoying9105** [MorvanZhou/Reinforcement-learning-with-tensorflow#8]
File "/usr/projects/Reinforcement-learning-with-tensorflow/experiments/2D_car/car_env.py", line 67
    self.car_info[:3] = np.array([*self.start_point, -np.pi / 2])
                                  ^
SyntaxError: invalid syntax

**Comment by MorvanZhou** [comment]
Please try configuring your editor.
