### ISSUE TITLE
4_Sarsa_lambda_maze这个教程的算法的一点小建议

### ISSUE THREAD

**Issue by xhxt2008** [MorvanZhou/Reinforcement-learning-with-tensorflow#82]
Reinforcement-learning-with-tensorflow/contents/4_Sarsa_lambda_maze/RL_brain.py 86行

```
# Method 2:
        self.eligibility_trace.loc[s, :] *= 0
        self.eligibility_trace.loc[s, a] = 1
```
每一次重新开始，会把走到的位置reset成0，但是没有走到的位置不会被重置，依然会在每次的参数更新中被迭代。这个问题我猜测可能会导致小方块一直停留在初始位置不敢动。

### 解决方法
只要在每次重置的时候，把trace全部赋值成0就行了。而不是只把经过的点变成0.

1. 只需要注释掉第96行
```
# Method 2:
       #  self.eligibility_trace.loc[s, :] *= 0
        self.eligibility_trace.loc[s, a] = 1
```
2. 然后在RL_brain.py里面新建一个函数

```
def init_eligibility_trace(self):
        self.eligibility_trace.iloc[:] = 0
```
3. 然后在run_this.py里面，while循环之前添加：
`RL.init_eligibility_trace()`

这样做程序的鲁棒性会更高。

另外非常感谢你的工作，这对我的学习很有帮助。

**Comment by MorvanZhou** [comment]
你好, 感谢您的反馈, 我记得当时我写 `self.eligibility_trace.loc[s, :] *= 0` 的时候也在犹豫要不要把s下全部的a都设为0, 我记得是在书里面看到了才这么做的. 如果真的带来的效果上的提升, 我觉得是可以不写那句话的.
