### ISSUE TITLE
关于action的数量是变化的，需要怎么处理？

### ISSUE THREAD

**Issue by liqinxiao** [MorvanZhou/Reinforcement-learning-with-tensorflow#83]
如果action的数量会根据observation变化，而不是固定的，这种action在输入神经网络前需要怎么处理？

**Comment by MorvanZhou** [comment]
你好，这暂时还么有一个很好的解决方法，
你可以尝试将不同数量的action装换成连续值action。如果能够转换成连续值action，那就能够使用像policy gradient这样的强化学习算法。
