### ISSUE TITLE
About how to feed action to critic

### ISSUE THREAD

**Issue by sasforce** [MorvanZhou/Reinforcement-learning-with-tensorflow#85]
莫烦：
您好。
请问优化critic网络时，需要将batch action和batch state数据喂给网络，您的代码是这样写的：
self.sess.run(self.ctrain, {self.S: bs, self.a: ba, self.R: br, self.S_: bs_})。
self.a不是tensor的占位符，请问这样写是否有问题？谢谢。

**Comment by MorvanZhou** [comment]
你好，self.a 虽然不是placeholder，但是一样可以被feed。如果你做一个这样的小实验，就可以发现有时候tensor是可以被当做placeholder的。

**Comment by sasforce** [comment]
> 你好，self.a 虽然不是placeholder，但是一样可以被feed。如果你做一个这样的小实验，就可以发现有时候tensor是可以被当做placeholder的。

好的，十分感谢!
