### ISSUE TITLE
EMA Getter in DDPG not getting called?

### ISSUE THREAD

**Issue by jandevries123** [MorvanZhou/Reinforcement-learning-with-tensorflow#89]
The function EMA Getter isn't getting called in the DDPG code? correct me if im wrong, but show where it is?

**Comment by MorvanZhou** [comment]
It is called by this two line:
```
a_ = self._build_a(self.S_, reuse=True, custom_getter=ema_getter)   # replaced target parameters
q_ = self._build_c(self.S_, a_, reuse=True, custom_getter=ema_getter)
```

**Comment by jandevries123** [comment]
thanks. also i tried hooking up an environment of myself on your fantastic DDPG Algorithme, everything "works" so far, the loop runs smoothly, but the weights aren't updating.... i know you useally don't bother with personal help not surrounding the project, but do you maybe know what it may caused? i didn't changed anything algorithme wise in the code.

**Comment by jandevries123** [comment]
Please be so kind to delete this issue for me, thank you in advance.
