### ISSUE TITLE
A3C_continuous_action.py每个线程均可更新全局网络参数，有冲突的可能吗？

### ISSUE THREAD

**Issue by exceeddream** [MorvanZhou/Reinforcement-learning-with-tensorflow#91]
A3C_continuous_action.py中，每个线程都可以更新全局网络参数。如果有2个线程同时更新全局网络参数，或者某个线程在更新全局网络参数，另1个线程在读取全局网络参数，会不会出现问题？ 代码中好像没有机制来避免这种情况。

代码中用到了COORD.should_stop()，但没有用到COORD.request_stop()，这个COORD.should_stop()是否可以去掉？

望回复，感谢！

**Comment by MorvanZhou** [comment]
你好，

如果不适用lock，的确会有同时读写的危险。但是使用lock，效率可能会更低，特别是worker很多的时候。如果每个worker对grad修改幅度很小，这种危险程度也小。

COORD.should_stop(） 可以被去掉。

**Comment by exceeddream** [comment]
非常感谢您！想再问2个问题：
1.  A3C_continuous_action.py每个线程都会计算Gradients，然后推送Gradients 给 Global net,更新全局网络参数。DPPO.py只有1个线程计算Gradients更新Global PPO，其他线程采集的数据给Global PPO。我看其他issue中您的回复，似乎DPPO的多线程方式更优？如果A3C也改成1个线程计算Gradients更新全局网络参数，其他线程只负责采集数据，会不会效率更高？

2. 在pytorch的A3C实现中用的total_loss = (c_loss + a_loss).mean()优化actor和critic网络参数，tensorflow是 a_loss和c_loss 分别优化actor和critic网络参数。是否分别优化更好一些？加在一起优化，会不会侧重于优化actor或critic中的某1个网络，造成另1个优化不足？

望回复，非常感谢！
