### ISSUE TITLE
Question about large amount of outputs

### ISSUE THREAD

**Issue by YuffieHuang** [MorvanZhou/Reinforcement-learning-with-tensorflow#95]
Hi Morvan,

I'm doing a project in which I want to control 4 different parameters at the same time. Each of the parameters varies between 0 and 1. Therefore, I tried to discretize each of them into 11 levels, and each of them would be {xi | xi = 0, 0.1, 0.2, ..., 0.9, 1, i = 1, 2, 3, 4}.

In this case, I would get 11^4 combinations in total and I want to take them as the outputs (actions) of a DQN. Would the action space be considered too large? Should I increase the number of the nodes in the hidden layers to deal with it?

Thank you so much for your help.

Best,
Yufei

**Comment by MorvanZhou** [comment]
Hi Yufei,

It is a generally large range to explore. Instead of discrete action, have you attempted to use continuous action space? If the discrete action is required, then you may need to increase the nodes and layers in order to increase the capacity of the net.
