### ISSUE TITLE
DDPG soft replacement zip 函数参数长度不匹配

### ISSUE THREAD

**Issue by ilzhtony** [MorvanZhou/Reinforcement-learning-with-tensorflow#96]
https://github.com/MorvanZhou/Reinforcement-learning-with-tensorflow/blob/81fea33905c7f81719ec031eab51c68225eb7cce/contents/9_Deep_Deterministic_Policy_Gradient_DDPG/DDPG_update.py#L63

本地输出这里的zip函数四个参数的长度分别是4、4、5、5，不匹配会导致critic target网络中一些参数不被更新。

**Comment by MorvanZhou** [comment]
谢谢发现问题，修改成这样就好了。
